cui_coupdecoeur_index:
    path:     /
    defaults: { _controller: CUICoupdecoeurBundle:Coupdecoeur:index }

cui_coupdecoeur_view:
    path: /v/{id}-{lien}
    defaults:
      _controller: CUICoupdecoeurBundle:Coupdecoeur:view
    requirements:
      id: '[0-9]+'
      lien: '^[a-zA-Z0-9_-]+\.html$'
