sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.youtube

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        sonata_collection:
            providers:
              - sonata.media.provider.image
              - sonata.media.provider.youtube

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
              - sonata.media.provider.image
              - sonata.media.provider.youtube

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

    cdn:
        server:
            path: /comuneimage/web/upload/images # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/upload/images"
            create:     false

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~
                    ApplicationSonataMediaBundle: ~